environments:
  default: &default
    model_name: seargenf2
    aws_role: 'AmazonSageMakerFullAccess'
  local:
    <<: *default
    instance_type: local
    model_data_path: 'build/model.tar.gz'
  production:
    <<: *default
    instance_type: ml.g4dn.xlarge
    model_data_path: s3://seargenf/model.tar.gz
